version: '3'

volumes:
  persistent-storage:
    driver: local

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=demo123
      - POSTGRES_DB=data
    volumes:
      - /home/sfl/devel/personal/database-access/data/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
        - persistent-storage:/data
    entrypoint: redis-server --appendonly yes
    ports:
      - 6379:6379